In [6]:
import pandas as pd
from utils.db import engine  # your SQLAlchemy engine

# 1) Write your ad‐hoc SQL
sql = """
WITH
  coach_cte AS (
    SELECT
      u.club_id,
      CASE
        WHEN EXTRACT(MONTH FROM u.created_at) >= 7 THEN
          CONCAT(EXTRACT(YEAR FROM u.created_at)::INT, '/', EXTRACT(YEAR FROM u.created_at)::INT + 1)
        ELSE
          CONCAT((EXTRACT(YEAR FROM u.created_at)::INT - 1), '/', EXTRACT(YEAR FROM u.created_at)::INT)
      END AS season,
      COUNT(*) AS coaches
    FROM users u
    WHERE u.role    = 'coach'
      AND u.active  IS TRUE
      AND u.club_id IS NOT NULL
    GROUP BY u.club_id, season
  ),

  parent_cte AS (
    SELECT
      u.club_id,
      CASE
        WHEN EXTRACT(MONTH FROM u.created_at) >= 7 THEN
          CONCAT(EXTRACT(YEAR FROM u.created_at)::INT, '/', EXTRACT(YEAR FROM u.created_at)::INT + 1)
        ELSE
          CONCAT((EXTRACT(YEAR FROM u.created_at)::INT - 1), '/', EXTRACT(YEAR FROM u.created_at)::INT)
      END AS season,
      COUNT(*) AS parents
    FROM users u
    WHERE u.role    = 'guardian'
      AND u.active  IS TRUE
      AND u.club_id IS NOT NULL
    GROUP BY u.club_id, season
  ),

  skier_cte AS (
    SELECT
      u.club_id,
      CASE
        WHEN EXTRACT(MONTH FROM u.created_at) >= 7 THEN
          CONCAT(EXTRACT(YEAR FROM u.created_at)::INT, '/', EXTRACT(YEAR FROM u.created_at)::INT + 1)
        ELSE
          CONCAT((EXTRACT(YEAR FROM u.created_at)::INT - 1), '/', EXTRACT(YEAR FROM u.created_at)::INT)
      END AS season,
      -- Count total skiers:
      COUNT(*) AS skiers,
      -- Count male ski ers only:
      COUNT(*) FILTER (WHERE lower(u.gender) = 'male')   AS male_skiers,
      -- Count female ski ers only:
      COUNT(*) FILTER (WHERE lower(u.gender) = 'female') AS female_skiers
    FROM users u
    WHERE u.role    = 'skier'
      AND u.active  IS TRUE
      AND u.club_id IS NOT NULL
    GROUP BY u.club_id, season
  ),

  contact_cte AS (
    SELECT
      u.club_id,
      season,
      primary_contact,
      primary_contact_email
    FROM (
      SELECT
        club_id,
        firstname || ' ' || lastname       AS primary_contact,
        email                              AS primary_contact_email,
        CASE
          WHEN EXTRACT(MONTH FROM created_at) >= 7 THEN
            CONCAT(EXTRACT(YEAR FROM created_at)::INT, '/', EXTRACT(YEAR FROM created_at)::INT + 1)
          ELSE
            CONCAT((EXTRACT(YEAR FROM created_at)::INT - 1), '/', EXTRACT(YEAR FROM created_at)::INT)
        END                                AS season,
        ROW_NUMBER() OVER (
          PARTITION BY club_id,
                       CASE
                         WHEN EXTRACT(MONTH FROM created_at) >= 7 THEN
                           CONCAT(EXTRACT(YEAR FROM created_at)::INT, '/', EXTRACT(YEAR FROM created_at)::INT + 1)
                         ELSE
                           CONCAT((EXTRACT(YEAR FROM created_at)::INT - 1), '/', EXTRACT(YEAR FROM created_at)::INT)
                       END
          ORDER BY created_at
        )                                  AS rn
      FROM users
      WHERE role    = 'coach'
        AND active  IS TRUE
        AND club_id IS NOT NULL
    ) u
    WHERE u.rn = 1
  ),

  seasons_union AS (
    SELECT club_id, season FROM coach_cte
    UNION
    SELECT club_id, season FROM parent_cte
    UNION
    SELECT club_id, season FROM skier_cte
  )

SELECT
  c.id                         AS club_id,
  su.season,
  c.name                       AS club_name,
  c.id                         AS sr_id,
  c.ptso                       AS ptso,
  COALESCE(co.coaches,  0)     AS coaches,
  COALESCE(pa.parents,   0)    AS parents,
  COALESCE(sk.skiers,    0)    AS skiers,
  -- New columns for gender breakdown:
  COALESCE(sk.male_skiers,   0) AS male_skiers,
  COALESCE(sk.female_skiers, 0) AS female_skiers,
  COALESCE(ct.primary_contact, '')       AS primary_contact,
  COALESCE(ct.primary_contact_email, '') AS primary_contact_email,
  'Active'                     AS status
FROM clubs c
JOIN seasons_union su
  ON su.club_id = c.id
LEFT JOIN coach_cte co
  ON co.club_id = c.id AND co.season = su.season
LEFT JOIN parent_cte pa
  ON pa.club_id = c.id AND pa.season = su.season
LEFT JOIN skier_cte sk
  ON sk.club_id = c.id AND sk.season = su.season
LEFT JOIN contact_cte ct
  ON ct.club_id = c.id AND ct.season = su.season
ORDER BY su.season, c.name;


"""

# 2) Load into a DataFrame
df = pd.read_sql(sql, engine)

# 3) Peek at the raw data
df.head(100)

,club_id,season,club_name,sr_id,ptso,coaches,parents,skiers,male_skiers,female_skiers,primary_contact,primary_contact_email,status
0,41,2024/2025,Adanac Ski Club,41,ontario,6,0,2,0,1,Bradley Laurin,blaurin08@icloud.com,Active
1,1,2024/2025,Alberta Alpine Ski Association,1,alberta,2,0,1,0,0,Curtis Rousseau,curtisrousseau@icloud.com,Active
2,2,2024/2025,Alberta Masters Ski Club,2,alberta,2,0,1,0,0,Andrew Ross,amhross@gmail.com,Active
3,134,2024/2025,Alberta Ski Cross,134,alberta,0,0,1,0,0,,,Active
4,133,2024/2025,Alpin Canada Ascension,133,canada,34,0,22,4,5,meribeth deen,meribeth.deen@gmail.com,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,208,2024/2025,Equipe De Course Edelweiss,208,quebec,8,0,2,0,1,Mario Hagnon,mpgagnonski@gmail.com,Active
96,123,2024/2025,Équipe De Ski Camp Fortune,123,quebec,3,0,5,2,2,Francois couture,coutsf60@gmail.com,Active
97,124,2024/2025,Équipe De Ski Force G Inc.,124,quebec,7,0,35,18,16,Aurélie messier,headcoachgleason@gmail.com,Active
98,209,2024/2025,Équipe De Ski La Tuque,209,quebec,1,0,1,0,0,Felix Lavergne,felix.lavergne@hotmail.ca,Active
99,125,2024/2025,Équipe Élite Alpin De L'Estrie,125,quebec,1,0,1,0,0,Philippe Duchesne,philf1duchesne@hotmsil.com,Active

,club_id,season,primary_contact,primary_contact_email
0,1,2024/2025,Curtis Rousseau,curtisrousseau@icloud.com
1,2,2024/2025,Andrew Ross,amhross@gmail.com
2,3,2024/2025,Blais O'Brien,u14headcoach@banffalpineracers.com
3,4,2024/2025,Brent MacDonald,james.brent.macdonald@gmail.com
4,6,2024/2025,Jennifer Cooke,jennifer.cooke8@gmail.com
5,7,2024/2025,Suzanne Sorensen,mrsblizzard@shaw.ca
6,8,2024/2025,Jarred Pawlowski,jarred.pawlowski@gmail.com
7,9,2024/2025,Mark Stein,m.stein@shaw.ca
8,11,2024/2025,matthew vance,mattdvance@msn.com
9,13,2024/2025,Hannah Penkala,hannahpenkala@gmail.com
10,14,2024/2025,gigi jacques,genevieve@lakelouiseskiclubs.ca
11,15,2024/2025,Emily Clarke,emily@lakelouiseskiclubs.ca
12,16,2024/2025,Jennifer Clarridge,jenniferclarridge@gmail.com
13,17,2024/2025,bill Quinney,bill_quinney2000@yahoo.com
14,19,2024/2025,Andrew Walker,andrew.walker@pepsico.com
15,20,2024/2025,Michael Hys-Moore,mhysmoore@gmail.com
16,22,2024/2025,Brian Bentt,bbentt@telus.net
17,23,2024/2025,Keira Rudge,keirarudge@gmail.com
18,24,2024/2025,jorja ottenbreit,jotten6@yahoo.ca
19,25,2024/2025,Michael Clark,clarkmick@gmail.com

In [10]:
df

Empty DataFrame
Columns: [level_name, skier_count]
Index: []